version: '3'
services: 
  postgres:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: postgres
    ports: 
      - "5430:5432"
    volumes: 
      - ./pgsql-data:/var/lib/postgresql/data
  webserver:
    build: ./
    ports: 
      - "8000:8000"